### ISSUE TITLE
Possible improvements

### ISSUE THREAD

**Issue by ProditorMagnus** [ProditorMagnus/WML_tree_tools#1]
- [ ] Try validate unit types that are referenced from factions and type #https://github.com/ProditorMagnus/Ageless-for-1-11/issues/28
- [ ] usage and recruitment_pattern match, warn if unit has type which does not exist in its faction, warn if pattern has type not found in its faction
- [x] Find duplicate abilities and movetype changes https://github.com/ProditorMagnus/Ageless-for-1-11/issues/25
- [x] Check attack range
- [ ] add validation that [unit_type][event] is not merged. Only parent [unit_type] can have events. No variation, gender, base_unit. https://github.com/wesnoth/wesnoth/issues/3827
- [ ] harm_unit where experience is not set, but unit exists
